name: Deploy Lambda Function

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js (if your Lambda function is a Node.js function)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust the version as needed

      # Install dependencies
      - name: Install dependencies
        run: npm install 

      # Deploy Lambda to AWS
      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          # Zip the Lambda function (assuming the code is in a folder called 'lambda')
          zip -r function.zip ./lambda
          
          # Deploy the Lambda function
          aws lambda update-function-code --function-name your-lambda-function-name --zip-file fileb://function.zip --region $AWS_REGION
